//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_OWASP_ASPNet_Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        public int idSubscription { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idCategory { get; set; }
    
        public virtual Categories Category { get; set; }
        public virtual Users User { get; set; }
    }
}
